# Generated by Django 3.2.25 on 2024-05-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
    ]
