# Generated by Django 3.2.25 on 2024-05-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publica',
            field=models.BooleanField(default=False),
        ),
    ]
